const $=id=>document.getElementById(id);let buffer,context,source,playingAt=0,previewDuration=0,animation,busy=false,title='音频',installEvent;
const local=location.hostname==='127.0.0.1'||location.hostname==='localhost';const service=local?location.origin:'http://127.0.0.1:47831';let serviceReady=false;
function say(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function ctx(){return context??=new AudioContext();}
function time(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(3).padStart(6,'0')}`;}
function bounds(){return [Number($('start').value),Number($('end').value)];}
function stop(){if(source){source.onended=null;source.stop();source=null;}cancelAnimationFrame(animation);$('play').textContent='▶ 试听选区';$('playhead').hidden=true;}
function update(start,end){if(!buffer)return;stop();const d=buffer.duration;start=Math.max(0,Math.min(d-.001,Number.isFinite(start)?start:0));end=Math.max(start+.001,Math.min(d,Number.isFinite(end)?end:d));$('start').value=start.toFixed(3);$('end').value=end.toFixed(3);$('startRange').value=start;$('endRange').value=end;$('selected').textContent=`已选 ${time(end-start)}`;$('selection').style.left=`${start/d*100}%`;$('selection').style.width=`${(end-start)/d*100}%`;}
function draw(){const canvas=$('wave'),w=canvas.clientWidth,h=canvas.clientHeight,r=devicePixelRatio||1;canvas.width=w*r;canvas.height=h*r;const p=canvas.getContext('2d');p.scale(r,r);p.strokeStyle='#e6e5ef';p.beginPath();p.moveTo(0,h/2);p.lineTo(w,h/2);p.stroke();if(!buffer)return;const data=buffer.getChannelData(0);p.fillStyle='#8c7bd9';for(let x=0;x<w;x+=4){const begin=Math.floor(x/w*data.length),end=Math.min(data.length,Math.floor((x+4)/w*data.length));let peak=0;for(let i=begin;i<end;i+=Math.max(1,Math.floor((end-begin)/80)))peak=Math.max(peak,Math.abs(data[i]));const bar=Math.max(2,peak*(h-28));p.fillRect(x,h/2-bar/2,2,bar);}}
function loaded(audio,name){buffer=audio;title=name;stop();$('filename').textContent=name;$('metadata').textContent=`${time(buffer.duration)} · ${Math.round(buffer.sampleRate/1000)} kHz`;$('duration').textContent=time(buffer.duration);$('half').textContent=time(buffer.duration/2);$('controls').disabled=false;$('reset').disabled=false;$('selection').hidden=false;$('empty').hidden=true;for(const id of ['start','end','startRange','endRange'])$(id).max=buffer.duration;update(0,buffer.duration);draw();say('音频已就绪。拖动紫色边界，或输入起止秒数来选取片段。');}
async function consume(blob,name){if(blob.size>80*1024*1024)throw Error('素材超过 80 MB，请先缩短视频或选择较小文件。');let audio;try{audio=await ctx().decodeAudioData(await blob.arrayBuffer());}catch(e){if(!serviceReady)throw Error('浏览器无法解码这个文件。请启动电脑转换服务后重试，或选择 MP3 / WAV 文件。');say('正在通过电脑转换服务提取音轨…');const res=await fetch(`${service}/api/transcode`,{method:'POST',headers:{'X-Soundcut':'1','Content-Type':'application/octet-stream'},body:blob});if(!res.ok)throw Error(await res.text());audio=await ctx().decodeAudioData(await res.arrayBuffer());}loaded(audio,name);}
async function job(fn){if(busy)return;busy=true;stop();$('fetch').disabled=true;$('demo').disabled=true;$('file').disabled=true;try{await fn();}catch(e){say(e.message||'处理失败，请重试。',true);}finally{busy=false;$('fetch').disabled=false;$('demo').disabled=false;$('file').disabled=false;}}
$('file').onchange=()=>{const file=$('file').files[0];if(file)job(async()=>{say('正在提取音轨并绘制波形…');await consume(file,file.name);});$('file').value='';};
$('urlForm').onsubmit=e=>{e.preventDefault();job(async()=>{const url=new URL($('url').value);if(!['https:','http:'].includes(url.protocol))throw Error('请使用 HTTP 或 HTTPS 链接。');const host=url.hostname.replace(/^www\./,'');if(['youtube.com','m.youtube.com','youtu.be','bilibili.com','m.bilibili.com','b23.tv'].includes(host)){if(!serviceReady)throw Error('YouTube / B站需要电脑转换服务。请打开下载包中的“启动声段.cmd”，再点击“连接转换服务”。');say('正在解析网页并提取音频，较长视频需要一些时间…');const res=await fetch(`${service}/api/extract`,{method:'POST',headers:{'X-Soundcut':'1','Content-Type':'application/json'},body:JSON.stringify({url:url.href})});if(!res.ok)throw Error(await res.text());const name=decodeURIComponent(res.headers.get('X-Audio-Title')||'网页视频');await consume(await res.blob(),name);return;}say('正在读取媒体链接…');let res;try{res=await fetch(url.href,{credentials:'omit',signal:AbortSignal.timeout(120000)});}catch{throw Error('无法读取该链接。请检查网址；来源网站也可能禁止跨域读取，可改用本地文件。');}if(!res.ok)throw Error(`读取失败（${res.status}）。`);if((res.headers.get('content-type')||'').includes('text/html'))throw Error('这是网页地址。当前网页解析支持 YouTube 和 B站，其他来源请导入本地文件。');const length=Number(res.headers.get('content-length'));if(length>80*1024*1024)throw Error('文件超过 80 MB。');const reader=res.body.getReader(),chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>80*1024*1024){await reader.cancel();throw Error('文件超过 80 MB。');}chunks.push(value);}await consume(new Blob(chunks),decodeURIComponent(url.pathname.split('/').pop())||'链接音频');});};
$('demo').onclick=()=>job(async()=>{const c=ctx(),b=c.createBuffer(1,c.sampleRate*12,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++){const t=i/c.sampleRate,f=[261.63,329.63,392,523.25][Math.floor(t*2)%4];a[i]=Math.sin(2*Math.PI*f*t)*Math.exp(-(t%0.5)*7)*.5;}loaded(b,'示例 · 十二秒旋律');update(2,7);});
for(const id of ['start','startRange'])$(id).oninput=()=>update(Number($(id).value),Number($('end').value));for(const id of ['end','endRange'])$(id).oninput=()=>update(Number($('start').value),Number($(id).value));$('reset').onclick=()=>update(0,buffer.duration);
for(const [id,isStart] of [['leftHandle',true],['rightHandle',false]]){$(id).onpointerdown=e=>{if(!buffer)return;e.preventDefault();$(id).setPointerCapture(e.pointerId);};$(id).onpointermove=e=>{if(!$(id).hasPointerCapture(e.pointerId))return;const box=$('waveWrap').getBoundingClientRect(),t=(e.clientX-box.left)/box.width*buffer.duration,[a,b]=bounds();update(isStart?Math.min(t,b-.001):a,isStart?b:Math.max(t,a+.001));};$(id).onpointerup=e=>{if($(id).hasPointerCapture(e.pointerId))$(id).releasePointerCapture(e.pointerId);};}
$('gain').oninput=()=>{$('gainLabel').textContent=`${Math.round(Number($('gain').value)*100)}%`;stop();};$('fade').onchange=stop;
function selectionPCM(){const [a,b]=bounds();return cutPCM(buffer,a,b,Number($('gain').value),$('fade').checked);}
$('play').onclick=async()=>{if(source){stop();return;}try{await ctx().resume();const channels=selectionPCM(),b=ctx().createBuffer(channels.length,channels[0].length,buffer.sampleRate);channels.forEach((v,i)=>b.copyToChannel(v,i));source=ctx().createBufferSource();source.buffer=b;source.loop=$('loop').checked;source.connect(ctx().destination);source.onended=stop;playingAt=ctx().currentTime;previewDuration=b.duration;source.start();$('play').textContent='■ 停止试听';$('playhead').hidden=false;function tick(){if(!source)return;const elapsed=(ctx().currentTime-playingAt)%previewDuration;$('playhead').style.left=`${(bounds()[0]+elapsed)/buffer.duration*100}%`;animation=requestAnimationFrame(tick);}tick();}catch(e){say(e.message,true);}};
$('loop').onchange=()=>{if(source)source.loop=$('loop').checked;};
$('export').onclick=()=>{try{const [a,b]=bounds(),blob=new Blob([encodeWav(selectionPCM(),buffer.sampleRate)],{type:'audio/wav'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${title.replace(/\.[a-z0-9]{2,5}$/i,'').replace(/[<>:"/\\|?*]/g,'_')}_${a.toFixed(2)}-${b.toFixed(2)}.wav`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);say(`已导出 ${time(b-a)} 的音频片段。`);}catch(e){say(e.message,true);}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;}else say('安装方法：在 Edge / Chrome 菜单中选择“安装此应用”；iPhone 请在 Safari 分享菜单中选择“添加到主屏幕”。');};
new ResizeObserver(draw).observe($('waveWrap'));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>say('离线缓存未启用，当前仍可在线使用。'));
async function connect(){try{const res=await fetch(`${service}/api/health`,{signal:AbortSignal.timeout(2500)});const info=await res.json();serviceReady=info.ready===true;$('connect').textContent=serviceReady?'转换服务已连接':'转换依赖未就绪';if(!serviceReady)say('请在电脑转换服务中完成依赖安装。',true);}catch{serviceReady=false;$('connect').textContent='连接转换服务';say('尚未连接电脑转换服务。启动下载包中的“启动声段.cmd”后重试；本地 MP3 / WAV 裁剪仍可使用。');}}
$('connect').onclick=connect;if(local)connect();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'set_audio_selection',description:'Set the start and end of the currently loaded audio selection in seconds. Does not export or download audio.',inputSchema:{type:'object',properties:{start:{type:'number'},end:{type:'number'}},required:['start','end'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!buffer)throw Error('No audio loaded');if(!Number.isFinite(input.start)||!Number.isFinite(input.end)||input.start<0||input.end>buffer.duration||input.end-input.start<.001)throw Error('Invalid time range');update(input.start,input.end);return {start:bounds()[0],end:bounds()[1],duration:bounds()[1]-bounds()[0]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
