'use strict';
const $=id=>document.getElementById(id);
const {formatTime:time,parseTime,validateRange,nearestMarker,previewRange}=AudioEditorMath;
const local=['127.0.0.1','localhost'].includes(location.hostname);
const service=local?location.origin:'http://127.0.0.1:47831';
let buffer,context,source,playback,animation,selectedStart=0,selectedEnd=0,cursor=0;
let markers=[],markerSequence=0,zoomFactor=1,viewStart=0,latchedMarker=null;
let title='音频',busy=false,serviceReady=false,installEvent,jobAbort,jobSequence=0,converter;
let preparedSelection=null,selectionVersion=0,playRequest=0;
const ctx=()=>context??=new AudioContext();
const bounds=()=>[selectedStart,selectedEnd];
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function clearSnap(){latchedMarker=null;$('selection').classList.remove('is-snapped');$('snapFeedback').classList.remove('active');$('snapFeedback').textContent='拖动边界靠近标记会吸附；按住 Alt 暂时关闭吸附。';}
const span=()=>buffer?buffer.duration/zoomFactor:1;
const percent=t=>(t-viewStart)/span()*100;
function say(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function currentPosition(){if(!source||!playback)return cursor;const elapsed=Math.max(0,ctx().currentTime-playback.startedAt),length=playback.end-playback.start;return playback.start+(source.loop?elapsed%length:Math.min(elapsed,length));}
function renderClock(){const t=currentPosition();$('clock').textContent=time(t);$('seek').value=t;const p=percent(t);$('playhead').hidden=!buffer||p<0||p>100;$('playhead').style.left=`${p}%`;}
function stop(keepPosition=true){++playRequest;if(source){if(keepPosition)cursor=currentPosition();source.onended=null;try{source.stop();}catch{}source.disconnect();playback?.gain?.disconnect();source=null;}playback=null;cancelAnimationFrame(animation);$('play').textContent='▶ 播放选区';$('playMode').textContent=buffer?'已暂停':'准备就绪';renderClock();}
function clearError(edge){$(edge).removeAttribute('aria-invalid');$(`${edge}Error`).hidden=true;}
function fieldError(edge,message){$(edge).setAttribute('aria-invalid','true');$(`${edge}Error`).textContent=message;$(`${edge}Error`).hidden=false;return false;}
function setRange(a,b,{pause=true,syncFields=true}={}){if(!buffer)return false;a=clamp(a,0,buffer.duration-.001);b=clamp(b,a+.001,buffer.duration);if(pause)stop();selectedStart=a;selectedEnd=b;const snapMark=markers.find(m=>m.id===latchedMarker);if(snapMark&&Math.abs(snapMark.time-a)>.00001&&Math.abs(snapMark.time-b)>.00001){clearSnap();renderMarkerLines();}selectionVersion++;preparedSelection=null;if(syncFields){$('start').value=a.toFixed(3);$('end').value=b.toFixed(3);clearError('start');clearError('end');}renderSelection();return true;}
function renderSelection(){if(!buffer)return;$('selection').style.left=`${percent(selectedStart)}%`;$('selection').style.width=`${(selectedEnd-selectedStart)/span()*100}%`;$('selected').textContent=`已选 ${time(selectedEnd-selectedStart)}`;for(const [edge,t]of [['start',selectedStart],['end',selectedEnd]]){$(`${edge}Range`).value=t;const h=$(edge==='start'?'leftHandle':'rightHandle');h.setAttribute('aria-valuenow',t.toFixed(3));h.setAttribute('aria-valuetext',time(t));h.setAttribute('aria-valuemax',buffer.duration.toFixed(3));h.hidden=t<viewStart||t>viewStart+span();}renderClock();}
function commitField(edge){if(!buffer)return true;const value=parseTime($(edge).value),a=edge==='start'?value:selectedStart,b=edge==='end'?value:selectedEnd;if(!Number.isFinite(value))return fieldError(edge,'请输入秒数（12.345）或分:秒（1:12.345）。');if(!validateRange(a,b,buffer.duration))return fieldError(edge,edge==='start'?`起点需在 0 到 ${(selectedEnd-.001).toFixed(3)} 秒之间。`:`终点需晚于起点，且不超过 ${buffer.duration.toFixed(3)} 秒。`);if(Math.abs(value-(edge==='start'?selectedStart:selectedEnd))>1e-7)setRange(a,b,{syncFields:false});$(edge).value=value.toFixed(3);clearError(edge);return true;}
function readyFields(){for(const edge of ['start','end'])if($(edge).getAttribute('aria-invalid')==='true'){say('请先修正时间输入，或按 Esc 恢复。',true);$(edge).focus();return false;}return true;}
for(const edge of ['start','end']){$(edge).addEventListener('blur',()=>commitField(edge));$(edge).addEventListener('input',()=>clearError(edge));$(edge).addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();if(commitField(edge))$(edge).blur();}else if(event.key==='Escape'){$(edge).value=(edge==='start'?selectedStart:selectedEnd).toFixed(3);clearError(edge);$(edge).blur();}});}
function viewAt(t){if(!buffer)return;viewStart=clamp(t-span()/2,0,buffer.duration-span());renderView();}
function renderView(){if(!buffer)return;viewStart=clamp(viewStart,0,buffer.duration-span());$('viewFrom').textContent=time(viewStart);$('half').textContent=time(viewStart+span()/2);$('duration').textContent=time(viewStart+span());$('viewControls').hidden=zoomFactor===1;$('pan').max=Math.max(0,buffer.duration-span());$('pan').value=viewStart;draw();renderSelection();renderMarkerLines();}
function draw(){const canvas=$('wave'),w=canvas.clientWidth,h=canvas.clientHeight,r=devicePixelRatio||1;canvas.width=w*r;canvas.height=h*r;const p=canvas.getContext('2d');p.scale(r,r);p.strokeStyle='#e6e5ef';p.beginPath();p.moveTo(0,h/2);p.lineTo(w,h/2);p.stroke();if(!buffer)return;const data=buffer.getChannelData(0);p.fillStyle='#8c7bd9';for(let x=0;x<w;x+=3){const begin=Math.floor((viewStart+x/w*span())*buffer.sampleRate),end=Math.min(data.length,Math.ceil((viewStart+(x+3)/w*span())*buffer.sampleRate));let peak=0;for(let i=begin;i<end;i+=Math.max(1,Math.floor((end-begin)/100)))peak=Math.max(peak,Math.abs(data[i]));const height=Math.max(2,peak*(h-42));p.fillRect(x,h/2-height/2,2,height);}}
function renderMarkerLines(){$('markerLines').replaceChildren();for(const m of markers){if(m.time<viewStart||m.time>viewStart+span())continue;const line=document.createElement('button');line.type='button';line.className='marker-line'+(latchedMarker===m.id?' snapped':'');line.style.left=`${percent(m.time)}%`;line.setAttribute('aria-label',`跳转到标记 ${m.label}，${time(m.time)}`);const flag=document.createElement('span');flag.textContent=m.label;line.append(flag);line.addEventListener('pointerdown',e=>e.stopPropagation());line.onclick=()=>seekTo(m.time);$('markerLines').append(line);}}
function renderMarkers(){$('markerCount').textContent=markers.length;$('markerList').replaceChildren();if(!markers.length){const p=document.createElement('p');p.className='marker-empty';p.textContent='播放时标记想保留的瞬间，声音不会中断。';$('markerList').append(p);}for(const m of markers){const row=document.createElement('div');row.className='marker-row';const jump=document.createElement('button');jump.className='marker-jump';jump.textContent=`${m.label}  ${time(m.time)}`;jump.onclick=()=>{seekTo(m.time);viewAt(m.time);};row.append(jump);for(const [label,edge]of [['设为起点','start'],['设为终点','end']]){const b=document.createElement('button');b.textContent=label;b.className='quiet';b.onclick=()=>setEdge(edge,m.time,true);row.append(b);}const remove=document.createElement('button');remove.className='quiet';remove.textContent='×';remove.setAttribute('aria-label',`删除标记 ${m.label}`);remove.onclick=()=>{markers=markers.filter(x=>x.id!==m.id);clearSnap();renderMarkers();};row.append(remove);$('markerList').append(row);}renderMarkerLines();}
function addMarker(){if(!buffer)return;const t=clamp(Math.round(currentPosition()*1000)/1000,0,buffer.duration);const duplicate=markers.find(m=>Math.abs(m.time-t)<.001);if(duplicate){say(`${duplicate.label} 已在 ${time(duplicate.time)}。`);return;}const id=++markerSequence;markers.push({id,label:`M${id}`,time:t});markers.sort((a,b)=>a.time-b.time);renderMarkers();say(`已标记 M${id} · ${time(t)}，播放继续。`);}
function snapValue(value,edge,enabled=true){const result=nearestMarker(value,markers,{width:$('waveWrap').clientWidth,span:span(),min:edge==='start'?0:selectedStart+.001,max:edge==='start'?selectedEnd-.001:buffer.duration,latched:latchedMarker,enabled:enabled&&$('snap').checked});const old=latchedMarker;latchedMarker=result.marker?.id??null;$('selection').classList.toggle('is-snapped',!!result.marker);$('snapFeedback').classList.toggle('active',!!result.marker);if(result.marker){$('snapFeedback').textContent=`${edge==='start'?'起点':'终点'}已吸附 ${result.marker.label} · ${time(result.marker.time)}`;if(old!==latchedMarker){navigator.vibrate?.(15);renderMarkerLines();}}else if(old!==null){$('snapFeedback').textContent='拖动边界靠近标记会吸附；按住 Alt 暂时关闭吸附。';renderMarkerLines();}return result.time;}
function setEdge(edge,value,exact=false){if(!buffer)return false;const min=edge==='start'?0:selectedStart+.001,max=edge==='start'?selectedEnd-.001:buffer.duration;if(exact&&(value<min||value>max)){say(edge==='start'?'这个标记晚于当前终点，请先调整终点。':'这个标记早于当前起点，请先调整起点。',true);return false;}value=clamp(value,min,max);setRange(edge==='start'?value:selectedStart,edge==='end'?value:selectedEnd);return true;}
function seekTo(t){if(!buffer)return;const wasPlaying=!!source,kind=playback?.kind;stop();cursor=clamp(t,0,buffer.duration);renderClock();if(wasPlaying)play(kind==='source'||kind==='context'?'source':'selection',cursor);}
function selectionAudio(){if(preparedSelection?.version===selectionVersion)return preparedSelection.audio;const channels=cutPCM(buffer,selectedStart,selectedEnd,Number($('gain').value),$('fade').checked);const audio=ctx().createBuffer(channels.length,channels[0].length,buffer.sampleRate);channels.forEach((v,i)=>audio.copyToChannel(v,i));preparedSelection={version:selectionVersion,audio};return audio;}
async function play(kind='selection',from=null){if(!buffer||!readyFields())return;stop();const request=playRequest;try{await ctx().resume();if(request!==playRequest)return;const raw=kind==='source'||kind==='context';let [a,b]=kind==='source'?[from??cursor,buffer.duration]:previewRange(kind,selectedStart,selectedEnd,buffer.duration);if(kind==='selection'&&from!==null&&from>=a&&from<b-.001)a=from;if(b-a<.001){a=kind==='source'?0:selectedStart;}const audio=raw?buffer:selectionAudio();const offset=raw?a:a-selectedStart;source=ctx().createBufferSource();source.buffer=audio;source.loop=$('loop').checked;source.loopStart=offset;source.loopEnd=raw?b:b-selectedStart;const gain=ctx().createGain();gain.gain.value=raw?Number($('gain').value):1;source.connect(gain);gain.connect(ctx().destination);playback={kind,start:a,end:b,startedAt:ctx().currentTime,gain};cursor=a;source.onended=()=>{cursor=b;stop(false);$('playMode').textContent='试听结束';};if(source.loop)source.start(0,offset);else source.start(0,offset,b-a);$('play').textContent='Ⅱ 暂停';$('playMode').textContent=({source:'原音频',selection:'选中片段',head:'选区开头 3 秒',tail:'选区结尾 3 秒',context:'切点前 2 秒 / 后 1 秒 · 原音频'})[kind];if(a<viewStart||a>viewStart+span())viewAt(a);function tick(){if(!source)return;renderClock();animation=requestAnimationFrame(tick);}tick();}catch(e){stop();say(`无法播放：${e.message}`,true);}}
$('play').onclick=()=>source?stop():play('selection',cursor);
$('playSource').onclick=()=>play('source',cursor);
$('previewStart').onclick=()=>play('head');$('previewEnd').onclick=()=>play('tail');$('previewContext').onclick=()=>play('context');
$('loop').onchange=()=>{if(source){const kind=playback.kind;const current=currentPosition();play(kind,kind==='selection'||kind==='source'?current:null);}};
$('addMarker').onclick=addMarker;$('startAtCursor').onclick=()=>setEdge('start',currentPosition(),true);$('endAtCursor').onclick=()=>setEdge('end',currentPosition(),true);
$('seek').oninput=()=>seekTo(Number($('seek').value));$('reset').onclick=()=>setRange(0,buffer.duration);
$('zoom').onchange=()=>{const t=currentPosition();zoomFactor=Number($('zoom').value);viewAt(t);};$('pan').oninput=()=>{viewStart=Number($('pan').value);renderView();};$('locateStart').onclick=()=>viewAt(selectedStart);$('locateEnd').onclick=()=>viewAt(selectedEnd);
for(const edge of ['start','end']){$(`${edge}Range`).oninput=e=>setEdge(edge,snapValue(Number(e.target.value),edge,!e.altKey));}
for(const b of document.querySelectorAll('[data-delta]'))b.onclick=e=>setEdge(b.dataset.edge,(b.dataset.edge==='start'?selectedStart:selectedEnd)+Number(b.dataset.delta)*(e.shiftKey ? .1 : 1));
for(const [id,edge]of [['leftHandle','start'],['rightHandle','end']]){const handle=$(id);let grabOffset=0;handle.onpointerdown=e=>{if(!buffer)return;e.preventDefault();e.stopPropagation();const rect=$('waveWrap').getBoundingClientRect();grabOffset=viewStart+(e.clientX-rect.left)/rect.width*span()-(edge==='start'?selectedStart:selectedEnd);stop();latchedMarker=null;handle.setPointerCapture(e.pointerId);handle.classList.add('dragging');};handle.onpointermove=e=>{if(!handle.hasPointerCapture(e.pointerId))return;const rect=$('waveWrap').getBoundingClientRect();const t=viewStart+(e.clientX-rect.left)/rect.width*span()-grabOffset;setEdge(edge,snapValue(t,edge,!e.altKey));};const release=e=>{if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);handle.classList.remove('dragging');};handle.onpointerup=release;handle.onpointercancel=release;handle.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const delta=(e.shiftKey ? .001 : .01)*(['ArrowLeft','ArrowDown'].includes(e.key)?-1:1);setEdge(edge,(edge==='start'?selectedStart:selectedEnd)+delta);};}
$('wave').onpointerdown=e=>{if(!buffer)return;const rect=$('waveWrap').getBoundingClientRect();seekTo(viewStart+(e.clientX-rect.left)/rect.width*span());};
function changeProcessing(){stop();selectionVersion++;preparedSelection=null;$('gainLabel').textContent=`${Math.round(Number($('gain').value)*100)}%`;}
$('gain').oninput=changeProcessing;$('fade').onchange=changeProcessing;
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable="true"]')||e.ctrlKey||e.metaKey||e.altKey||!buffer||busy)return;if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();source?stop():play('selection',cursor);}if(!e.repeat&&e.key.toLowerCase()==='m'){e.preventDefault();addMarker();}if(!e.repeat&&e.key.toLowerCase()==='i'){e.preventDefault();setEdge('start',currentPosition(),true);}if(!e.repeat&&e.key.toLowerCase()==='o'){e.preventDefault();setEdge('end',currentPosition(),true);}});
function loaded(audio,name){if(audio.duration<.001)throw Error('素材太短，无法裁剪。');stop();buffer=audio;title=name;cursor=0;markers=[];markerSequence=0;clearSnap();zoomFactor=1;viewStart=0;$('zoom').value='1';$('filename').textContent=name;$('metadata').textContent=`${time(buffer.duration)} · ${Math.round(buffer.sampleRate/1000)} kHz`;$('controls').disabled=false;$('reset').disabled=false;$('zoom').disabled=false;$('leftHandle').disabled=false;$('rightHandle').disabled=false;$('selection').hidden=false;$('empty').hidden=true;$('seek').max=buffer.duration;for(const id of ['startRange','endRange'])$(id).max=buffer.duration;setRange(0,buffer.duration);renderView();renderMarkers();$('playMode').textContent='可以开始试听';say('音频已就绪。播放时按 M 打标记，拖动边界即可吸附。');}
function progress(text,value){$('progressText').textContent=text;$('jobProgress').hidden=false;if(Number.isFinite(value))$('progress').value=clamp(value,0,100);else $('progress').removeAttribute('value');}
async function getConverter(){return converter??=await import('./converter.js');}
async function consume(blob,name,signal){if(blob.size>80*1024*1024)throw Error('素材超过 80 MB，请选择较小文件。');let audio;try{audio=await ctx().decodeAudioData(await blob.arrayBuffer());}catch{signal.throwIfAborted();progress('正在自动准备浏览器转换引擎…');const engine=await getConverter();const decoded=await engine.transcode(blob,name,{signal,onProgress:(text,value)=>{if(!signal.aborted)progress(text,value);}});signal.throwIfAborted();audio=await ctx().decodeAudioData(decoded);$('engineState').textContent='浏览器转换引擎已就绪 · 本地运行';}signal.throwIfAborted();loaded(audio,name);}
async function job(fn){if(busy)return;busy=true;stop();const id=++jobSequence;jobAbort=new AbortController();for(const key of ['fetch','demo','file','prepare'])$(key).disabled=true;progress('正在处理…');try{await fn(jobAbort.signal);}catch(e){if(id===jobSequence)say(e.name==='AbortError'?'已取消。可以重新选择素材。':e.message||'处理失败，请重试。',e.name!=='AbortError');}finally{if(id===jobSequence){busy=false;jobAbort=null;for(const key of ['fetch','demo','file','prepare'])$(key).disabled=false;$('jobProgress').hidden=true;}}}
$('cancel').onclick=()=>jobAbort?.abort();
$('file').onchange=()=>{const file=$('file').files[0];if(file)job(signal=>consume(file,file.name,signal));$('file').value='';};
$('prepare').onclick=()=>job(async signal=>{const engine=await getConverter();await engine.prepare({signal,onProgress:progress});signal.throwIfAborted();$('engineState').textContent='浏览器转换引擎已就绪 · 本地运行';say('已准备好转换引擎。导入本地视频即可使用，无需启动电脑脚本。');});
$('demo').onclick=()=>job(async()=>{const c=ctx(),b=c.createBuffer(1,c.sampleRate*30,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++){const t=i/c.sampleRate,f=[261.63,329.63,392,523.25][Math.floor(t*2)%4];a[i]=Math.sin(2*Math.PI*f*t)*Math.exp(-(t%0.5)*7)*.5;}loaded(b,'示例 · 三十秒旋律');setRange(2,12);cursor=2;renderClock();});
async function connect(quiet=false){try{const res=await fetch(`${service}/api/health`,{signal:AbortSignal.timeout(4000)});const info=await res.json();serviceReady=info.ready===true;$('connect').textContent=serviceReady?'电脑解析助手已连接':'助手依赖未就绪';if(!serviceReady&&!quiet)say('电脑解析助手尚未准备好。你仍可直接导入本地视频，转换引擎会自动准备。');return serviceReady;}catch{serviceReady=false;$('connect').textContent='连接电脑解析助手';if(!quiet)say('这台电脑尚未运行解析助手，或浏览器不允许访问本机。导入本地视频无需助手，转换引擎会自动下载；YouTube / B站页面仍需助手。');return false;}}
$('connect').onclick=()=>connect();if(local)connect(true);
$('urlForm').onsubmit=e=>{e.preventDefault();job(async signal=>{const url=new URL($('url').value);if(!['https:','http:'].includes(url.protocol))throw Error('请使用 HTTP 或 HTTPS 链接。');const host=url.hostname.replace(/^www\./,'');if(['youtube.com','m.youtube.com','youtu.be','bilibili.com','m.bilibili.com','b23.tv'].includes(host)){if(!serviceReady&&!await connect(true))throw Error('本地视频可直接自动转换。YouTube / B站请下载上方 Windows 解析助手，解压后双击“启动声段.cmd”；首次会自动准备依赖。');signal.throwIfAborted();progress('正在解析网页并提取音频…');const res=await fetch(`${service}/api/extract`,{method:'POST',headers:{'X-Soundcut':'1','Content-Type':'application/json'},body:JSON.stringify({url:url.href}),signal});if(!res.ok)throw Error(await res.text());await consume(await res.blob(),decodeURIComponent(res.headers.get('X-Audio-Title')||'网页视频'),signal);return;}progress('正在读取媒体链接…');let res;try{res=await fetch(url.href,{credentials:'omit',signal});}catch(e){if(e.name==='AbortError')throw e;throw Error('无法读取链接。来源网站可能禁止跨域读取，请改为导入本地文件。');}if(!res.ok)throw Error(`读取失败（${res.status}）。`);if((res.headers.get('content-type')||'').includes('text/html'))throw Error('这是网页地址。其他来源请使用媒体直链或导入本地文件。');if(Number(res.headers.get('content-length'))>80*1024*1024)throw Error('文件超过 80 MB。');const reader=res.body.getReader(),chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>80*1024*1024){await reader.cancel();throw Error('文件超过 80 MB。');}chunks.push(value);progress(`已读取 ${(size/1048576).toFixed(1)} MB`);}await consume(new Blob(chunks),decodeURIComponent(url.pathname.split('/').pop())||'链接音频',signal);});};
$('export').onclick=()=>{if(!buffer||!readyFields())return;try{const channels=cutPCM(buffer,selectedStart,selectedEnd,Number($('gain').value),$('fade').checked);const url=URL.createObjectURL(new Blob([encodeWav(channels,buffer.sampleRate)],{type:'audio/wav'}));const link=document.createElement('a');link.href=url;link.download=`${title.replace(/\.[a-z0-9]{2,5}$/i,'').replace(/[<>:"/\\|?*]/g,'_')}_${selectedStart.toFixed(3)}-${selectedEnd.toFixed(3)}.wav`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);say(`已导出 ${time(selectedEnd-selectedStart)} 的音频片段。`);}catch(e){say(e.message,true);}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;}else say('在 Edge / Chrome 菜单中选择“安装此应用”；iPhone 请在 Safari 分享菜单中选择“添加到主屏幕”。');};
new ResizeObserver(()=>{draw();renderSelection();renderMarkerLines();}).observe($('waveWrap'));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>say('离线缓存未启用，仍可在线使用。'));
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'set_audio_selection',description:'Set the loaded audio selection in seconds. Does not export audio.',inputSchema:{type:'object',properties:{start:{type:'number'},end:{type:'number'}},required:['start','end'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!buffer)throw Error('No audio loaded');if(!validateRange(input.start,input.end,buffer.duration))throw Error('Invalid time range');setRange(input.start,input.end);return {start:selectedStart,end:selectedEnd,duration:selectedEnd-selectedStart};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
