const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
const ROOT=__dirname,PORT=47831,HOST='127.0.0.1',ORIGIN=`http://${HOST}:${PORT}`,ALLOWED=new Set([ORIGIN,`http://localhost:${PORT}`,'https://nero1100.github.io']),BIN=path.join(ROOT,'bin'),TMP=fs.mkdtempSync(path.join(os.tmpdir(),'soundcut-')),MAX=80*1024*1024;
const ffmpeg=path.join(BIN,'ffmpeg.exe'),ytdlp=path.join(BIN,'yt-dlp.exe');let active=false;
function run(exe,args){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{windowsHide:true,shell:false});let output='';const timer=setTimeout(()=>{child.kill();reject(Error('处理超时，请尝试较短的视频。'));},300000);child.stdout.on('data',v=>{output=(output+v).slice(-6000);});child.stderr.on('data',v=>{output=(output+v).slice(-6000);});child.on('error',()=>{clearTimeout(timer);reject(Error('转换依赖缺失，请重新运行安装脚本。'));});child.on('close',code=>{clearTimeout(timer);if(code===0)resolve(output);else reject(Error(/Sign in|login|cookies|403|412|429|bot/i.test(output)?'来源网站要求登录、验证或限制访问，当前无法提取。请下载后导入本地文件。':'无法提取音轨。链接可能无效、视频受限或格式不支持。'));});});}
async function body(req,limit){const list=[];let n=0;for await(const part of req){n+=part.length;if(n>limit)throw Error('素材过大，请选择 80 MB 以内的文件。');list.push(part);}return Buffer.concat(list);}
function reply(res,code,data,type='text/plain; charset=utf-8'){res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(data);}
function platform(url){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.port)throw Error('请提供 HTTPS 视频页面地址。');if(!['www.youtube.com','youtube.com','m.youtube.com','youtu.be','www.bilibili.com','bilibili.com','m.bilibili.com','b23.tv'].includes(u.hostname))throw Error('网页解析仅支持 YouTube 和 B站。');if(u.hostname==='bilibili.com')u.hostname='www.bilibili.com';return u.href;}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;if(req.headers.host!==`127.0.0.1:${PORT}`&&req.headers.host!==`localhost:${PORT}`)return reply(res,403,'Host denied');if(origin&&!ALLOWED.has(origin))return reply(res,403,'Origin denied');if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Soundcut');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Expose-Headers','X-Audio-Title');res.setHeader('Access-Control-Allow-Private-Network','true');}if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}const url=new URL(req.url,ORIGIN);
if(url.pathname==='/api/health')return reply(res,200,JSON.stringify({ready:fs.existsSync(ffmpeg)&&fs.existsSync(ytdlp)}),'application/json');
if(req.method==='POST'&&['/api/extract','/api/transcode'].includes(url.pathname)){if(!origin||!ALLOWED.has(origin)||req.headers['x-soundcut']!=='1')return reply(res,403,'Origin denied');if(active)return reply(res,409,'正在处理另一份素材，请稍后重试。');active=true;const dir=fs.mkdtempSync(path.join(TMP,'job-'));try{let input,name='网页音频';if(url.pathname==='/api/extract'){const {url:link}=JSON.parse((await body(req,4096)).toString());const verified=platform(link);await run(ytdlp,['--ignore-config','--no-playlist','--no-warnings','--max-filesize','80M','--match-filter','!is_live & duration <= 1800','--socket-timeout','25','--retries','1','--js-runtimes',`node:${process.execPath}`,'--ffmpeg-location',BIN,'-f','bestaudio/best','--write-info-json','-o',path.join(dir,'source.%(ext)s'),'--',verified]);const info=fs.readdirSync(dir).find(f=>f.endsWith('.info.json'));if(info){const meta=JSON.parse(fs.readFileSync(path.join(dir,info),'utf8'));name=meta.title||name;}const media=fs.readdirSync(dir).find(f=>!f.endsWith('.json')&&!f.endsWith('.part')&&!f.endsWith('.ytdl'));if(!media)throw Error('视频超过 30 分钟、80 MB，或无法获取音轨。');input=path.join(dir,media);}else{input=path.join(dir,'input.media');fs.writeFileSync(input,await body(req,MAX));name='本地视频音轨';}const duration=Number((await run(path.join(BIN,'ffprobe.exe'),['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',input])).trim());if(!Number.isFinite(duration)||duration>1800)throw Error('请使用 30 分钟以内的视频。');const output=path.join(dir,'audio.m4a');await run(ffmpeg,['-hide_banner','-loglevel','error','-nostdin','-protocol_whitelist','file,pipe','-i',input,'-map','0:a:0','-vn','-ac','2','-ar','44100','-c:a','aac','-b:a','192k','-y',output]);const audio=fs.readFileSync(output);if(audio.length>MAX)throw Error('转换后的音频过大，请缩短视频。');res.setHeader('X-Audio-Title',encodeURIComponent(name));reply(res,200,audio,'audio/mp4');}catch(e){reply(res,400,e.message);}finally{fs.rmSync(dir,{recursive:true,force:true});active=false;}return;}
if(req.method!=='GET')return reply(res,405,'Method not allowed');let file;try{file=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));}catch{return reply(res,400,'Invalid path');}const publicRoot=path.join(ROOT,'dist');const resolved=path.resolve(publicRoot,file);if(!resolved.startsWith(publicRoot+path.sep)||!['.html','.css','.js','.webmanifest','.svg','.png','.txt'].includes(path.extname(resolved)))return reply(res,404,'Not found');const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};try{reply(res,200,fs.readFileSync(path.join(ROOT,'dist',file)),types[path.extname(file)]);}catch{reply(res,404,'Not found');}});
server.requestTimeout=300000;server.listen(PORT,HOST,()=>console.log(`Soundcut ready: ${ORIGIN}`));server.on('error',e=>{console.error(e.message);process.exitCode=1;});process.on('exit',()=>fs.rmSync(TMP,{recursive:true,force:true}));
